name: C/C++ CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest
      
      
        
    - name: run GCC
      run: 
        gcc HelloWorld.cpp
    - name: run a.out
      run:
        ./a.out
             
