name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
permissions:
        contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest
      
      
        
    - name: run GCC
      run: 
        g++ HelloWorld.cpp
    - name: run a.out
      run:
        ./a.out
        
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: a.out
 
    - name: Create Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
        git push origin "v${{ github.run_number }}"
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: release/my-artifact.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
