name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
permissions:
        contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest
      
      
        
    - name: run GCC
      run: 
        g++ HelloWorld.cpp
    - name: run a.out
      run:
        ./a.out
        
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: a.out
 
    - name: Configure git to use GitHub Actions token
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Create a new tag and push it
      run: |
          git tag -a "v12" -m "Release v12"
          git push origin "v12"
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: release/my-artifact.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
