name: Build
on: 
  workflow_dispatch:

    inputs:
      FileName:
        type: choice
        description: For c++ file
        options: 
        - Hello.cpp
        - HelloArmenia.cpp
        - HelloWorld.cpp
     
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
   
permissions:
        contents: write


   
jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest
    
    - name: run GCC
      run: 
        g++ ${{inputs.FileName}}
    - name: sleep
      run:
         sleep 60
    - name: run a.out
      run:
        ./a.out
        
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: a.out
 
    - name: Configure git to use GitHub Actions token
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: 'Get Previous tag'
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
      
    - name: Release  
    
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
