on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
   
permissions:
        contents: write

   
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest

